/**
 * Marlin 3D Drucker Firmware
 * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin ]
 *
 * Basierend auf Sprinter und grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * Dieses Programm ist freie Software: Sie können es weiterverbreiten und/oder 
 * modifizieren unter den Bedingungen der GNU General Public License wie 
 * von der Free Software Foundation veröffentlicht, entweder Version 3 der Lizenz 
 * oder (nach Ihrer Wahl) jeder späteren Version.
 *
 * Dieses Programm wird in der Hoffnung verteilt, dass es nützlich sein wird,
 * jedoch OHNE JEDE GEWÄHRLEISTUNG; sogar ohne die implizite Gewährleistung 
 * der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK. Siehe die
 * GNU General Public License für weitere Details.
 *
 * Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
 * Programm erhalten haben. Falls nicht, siehe <https://www.gnu.org/licenses/ >.
 *
 */
#pragma once
//****************Deutsch***************************//
#define MACHINE_CONFIG_EN              "Konfiguration"
#define NEXT_EN                 "Weiter"
#define PREVIOUS_EN             "Zurück"
#define DEFAULT_EN              "Standard"
#define KEY_BACK_EN             "Löschen"
#define KEY_REST_EN             "Zurücksetzen"
#define KEY_CONFIRM_EN          "Bestätigen"
#define KEYBOARD_KEY0_EN "0"
#define KEYBOARD_KEY1_EN "1"
#define KEYBOARD_KEY2_EN "2"
#define KEYBOARD_KEY3_EN "3"
#define KEYBOARD_KEY4_EN "4"
#define KEYBOARD_KEY5_EN "5"
#define KEYBOARD_KEY6_EN "6"
#define KEYBOARD_KEY7_EN "7"
#define KEYBOARD_KEY8_EN "8"
#define KEYBOARD_KEY9_EN "9"
#define KEYBOARD_KEY_POINT_EN "."
#define KEYBOARD_KEY_NEGATIVE_EN "-"
#define MACHINE_PARA_TITLE_EN       "Konfiguration"
#define MACHINE_TYPE_CNOFIG_EN      "Maschineneinstellungen"
#define MOTOR_CONFIG_EN             "Motoreinstellungen"
#define MACHINE_LEVELING_CONFIG_EN  "Ebenheitseinstellungen"
#define ADVANCE_CONFIG_EN           "Erweiterte Einstellungen"
#define MACHINE_CONFIG_TITLE_EN     "Maschineneinstellungen"
#define MACHINE_TYPE_EN             "Maschinentyp"
#define MACHINE_STROKE_EN           "Maschinengröße"
#define MACHINE_HOMEDIR_EN          "Referenzfahrtrichtung"
#define MACHINE_ENDSTOP_TYPE_EN     "Endschaltertyp"
#define MACHINE_FILAMENT_CONFIG_EN  "Filamenteinstellungen"
#define MACHINE_TYPE_CONFIG_TITLE_EN    "Maschineneinstellungen>Maschinentyp"
#define MACHINE_TYPE_XYZ_EN             "XYZ-Maschine"
#define MACHINE_TYPE_DELTA_EN           "Delta-Maschine"
#define MACHINE_TYPE_COREXY_EN          "Corexy-Maschine"
#define MACHINE_STROKE_CONF_TITLE_EN    "Maschineneinstellungen>Maschinengröße"
#define X_MAX_LENGTH_EN                 "X-Achsen maximale Hublänge"
#define Y_MAX_LENGTH_EN                 "Y-Achsen maximale Hublänge"
#define Z_MAX_LENGTH_EN                 "Z-Achsen maximale Hublänge"
#define X_MIN_LENGTH_EN                 "X-Achsen minimale Hublänge"
#define Y_MIN_LENGTH_EN                 "Y-Achsen minimale Hublänge"
#define Z_MIN_LENGTH_EN                 "Z-Achsen minimale Hublänge"
#define HOME_DIR_CONF_TITLE_EN          "Maschineneinstellungen>Referenzfahrtrichtung"
#define HOME_DIR_X_EN                   "X-Achsen Referenzfahrtrichtung"
#define HOME_DIR_Y_EN                   "Y-Achsen Referenzfahrtrichtung"
#define HOME_DIR_Z_EN                   "Z-Achsen Referenzfahrtrichtung"
#define HOME_MIN_EN                     "MIN"
#define HOME_MAX_EN                     "MAX"
#define ENDSTOP_CONF_TITLE_EN           "Maschineneinstellungen>Endschaltertyp"
#define MIN_ENDSTOP_X_EN                "X-Achsen Minimumendschalter"
#define MIN_ENDSTOP_Y_EN                "Y-Achsen Minimumendschalter"
#define MIN_ENDSTOP_Z_EN                "Z-Achsen Minimumendschalter"
#define MAX_ENDSTOP_X_EN                "X-Achsen Maximumendschalter"
#define MAX_ENDSTOP_Y_EN                "Y-Achsen Maximumendschalter"
#define MAX_ENDSTOP_Z_EN                "Z-Achsen Maximumendschalter"
#define ENDSTOP_FIL_EN                  "Filamentsensor"
#define ENDSTOP_LEVEL_EN                "Ebenheitssensor"
#define ENDSTOP_OPENED_EN               "Geöffnet"
#define ENDSTOP_CLOSED_EN               "Geschlossen"
#define FILAMENT_CONF_TITLE_EN          "Maschineneinstellungen>Filamenteinstellungen"
#define FILAMENT_IN_LENGTH_EN           "Längeneinstellung beim Laden"
#define FILAMENT_IN_SPEED_EN            "Geschwindigkeit beim Laden"
#define FILAMENT_TEMPERATURE_EN         "Filamenttemperatur"
#define FILAMENT_OUT_LENGTH_EN          "Längeneinstellung beim Entladen"
#define FILAMENT_OUT_SPEED_EN           "Geschwindigkeit beim Entladen"
#define LEVELING_CONF_TITLE_EN          "Maschineneinstellungen>Ebenheitseinstellungen"
#define LEVELING_PARA_CONF_EN           "Ebenheitseinstellungen"
#define TRAMMING_POS_EN                 "Manuelle Nivellierkoordinateneinstellungen"
#define LEVELING_AUTO_COMMAND_EN        "Befehlseinstellungen für automatische Ebenheit"
#define LEVELING_AUTO_ZOFFSET_EN        "Einstellungen für Düsen-zu-Sensor Abstand"
#define LEVELING_ZOFFSET_TITLE_EN       "Maschineneinstellungen>Z-Offset-Assistent"
#define LEVELING_PARA_CONF_TITLE_EN     "Ebenheitseinstellungen"
#define AUTO_LEVELING_ENABLE_EN         "Automatische Ebenheit aktivieren"
#define BLTOUCH_LEVELING_ENABLE_EN      "BLTouch aktivieren"
#define PROBE_PORT_EN                   "Sensorstecker"
#define PROBE_X_OFFSET_EN               "X-Achsen Sensoroffset"
#define PROBE_Y_OFFSET_EN               "Y-Achsen Sensoroffset"
#define PROBE_Z_OFFSET_EN               "Z-Achsen Sensoroffset"
#define PROBE_XY_SPEED_EN               "Sensor XY-Achsen Geschwindigkeit"
#define PROBE_Z_SPEED_EN                "Sensor Z-Achsen Geschwindigkeit"
#define ENABLE_EN                       "JA"
#define DISABLE_EN                      "NEIN"
#define LOCKED_EN                       "N/V"
#define Z_MIN_EN                        "ZMin"
#define Z_MAX_EN                        "ZMax"
#define DELTA_LEVEL_CONF_TITLE_EN       "Delta-Maschineneinstellungen"
#define DELTA_LEVEL_CONF_EN             "Delta-Maschinen-Nivellierung"
#define DELTA_MACHINE_RADIUS_EN         "Maschinenradius"
#define DELTA_DIAGONAL_ROD_EN           "Stangenlänge"
#define DELTA_PRINT_RADIUS_EN           "Druckradius"
#define DELTA_HEIGHT_EN                 "Druckhöhe"
#define SMOOTH_ROD_OFFSET_EN            "Schlittenoffset"
#define EFFECTOR_OFFSET_EN              "Effector Offset"
#define CALIBRATION_RADIUS_EN           "Kalibrierungsraduis"
#define XYZ_LEVEL_CONF_TITLE_EN         "Kartesisches Maschinenkonfiguration"
#define PROBE_REACH_MAX_LEFT_EN         "Sensor erreicht äußerste linke Position"
#define PROBE_REACH_MAX_RIGHT_EN        "Sensor erreicht äußerste rechte Position"
#define PROBE_REACH_MAX_FRONT_EN        "Sensor erreicht vordere Position"
#define PROBE_REACH_MAX_BACK_EN         "Sensor erreicht hinterste Position"
#define TEMPERATURE_CONF_TITLE_EN       "Maschineneinstellungen>Temperatur"
#define NOZZLE_CONF_EN                  "Düsenkonfiguration"
#define HOTBED_CONF_EN                  "Heizbettkonfiguration"
#define PREHEAT_TEMPER_EN               "Voreingestellte Temperatur"
#define NOZZLE_CONF_TITLE_EN            "Maschineneinstellungen>Düsenkonfiguration"
#define NOZZLECNT_EN                    "Anzahl der Düsen"
#define NOZZLE_TYPE_EN                  "E0 Temperaturtyp"
#define NOZZLE_ADJUST_TYPE_EN           "PID Thermostat"
#define NOZZLE_MIN_TEMPERATURE_EN       "Minimale Temperatur"
#define NOZZLE_MAX_TEMPERATURE_EN       "Maximale Temperatur"
#define EXTRUD_MIN_TEMPER_EN            "Minimale Extrusionstemperatur"
#define HOTBED_CONF_TITLE_EN            "Maschineneinstellungen>Heizbett"
#define HOTBED_ADJUST_EN                "PID Thermostat"
#define HOTBED_MIN_TEMPERATURE_EN       "Minimale Temperatur"
#define HOTBED_MAX_TEMPERATURE_EN       "Maximale Temperatur"
#define MOTOR_CONF_TITLE_EN             "Maschineneinstellungen>Motoren"
#define MAXFEEDRATE_CONF_EN             "Maximale Geschwindigkeitseinstellungen"
#define ACCELERATION_CONF_EN            "Beschleunigungseinstellungen"
#define JERKCONF_EN                     "Ruckgeschwindigkeits-Einstellungen"
#define STEPSCONF_EN                    "Schrittzahl-Einstellungen"
#define TMC_CURRENT_EN                  "TMC Stromstärke-Einstellungen"
#define TMC_STEP_MODE_EN                "TMC Schrittmodes"
#define MOTORDIRCONF_EN                 "Motorrichtungseinstellungen"
#define HOMEFEEDRATECONF_EN             "Referenzfahrgeschwindigkeit"
#define MAXFEEDRATE_CONF_TITLE_EN       "Maschineneinstellungen>Maximale Geschwindigkeit"
#define X_MAXFEEDRATE_EN                "X-Achsen maximale Geschwindigkeit"
#define Y_MAXFEEDRATE_EN                "Y-Achsen maximale Geschwindigkeit"
#define Z_MAXFEEDRATE_EN                "Z-Achsen maximale Geschwindigkeit"
#define E0_MAXFEEDRATE_EN               "E0 maximale Geschwindigkeit"
#define E1_MAXFEEDRATE_EN               "E1 maximale Geschwindigkeit"
#define ACCELERATION_CONF_TITLE_EN      "Maschineneinstellungen>Beschleunigung"
#define PRINT_ACCELERATION_EN           "Druckbeschleunigung"
#define RETRACT_ACCELERATION_EN         "Retract-Beschleunigung"
#define TRAVEL_ACCELERATION_EN          "Fahrbewegungsbeschleunigung"
#define X_ACCELERATION_EN               "X-Achsen Beschleunigung"
#define Y_ACCELERATION_EN               "Y-Achsen Beschleunigung"
#define Z_ACCELERATION_EN               "Z-Achsen Beschleunigung"
#define E0_ACCELERATION_EN              "E0 Beschleunigung"
#define E1_ACCELERATION_EN              "E1 Beschleunigung"
#define JERK_CONF_TITLE_EN              "Maschineneinstellungen>Ruckgeschwindigkeit"
#define X_JERK_EN                       "X-Achsen Ruckgeschwindigkeit"
#define Y_JERK_EN                       "Y-Achsen Ruckgeschwindigkeit"
#define Z_JERK_EN                       "Z-Achsen Ruckgeschwindigkeit"
#define E_JERK_EN                       "Extruder-Ruckgeschwindigkeit"
#define STEPS_CONF_TITLE_EN             "Maschineneinstellungen>Schrittzahl"
#define X_STEPS_EN                      "X-Achsen Schritte"
#define Y_STEPS_EN                      "Y-Achsen Schritte"
#define Z_STEPS_EN                      "Z-Achsen Schritte"
#define E0_STEPS_EN                     "E0 Schritte"
#define E1_STEPS_EN                     "E1 Schritte"
#define TMC_CURRENT_CONF_TITLE_EN       "Maschineneinstellungen>TMC Stromstärke"
#define X_TMC_CURRENT_EN                "X-Achsen Stromstärke (mA)"
#define Y_TMC_CURRENT_EN                "Y-Achsen Stromstärke (mA)"
#define Z_TMC_CURRENT_EN                "Z-Achsen Stromstärke (mA)"
#define E0_TMC_CURRENT_EN               "E0 Stromstärke (mA)"
#define E1_TMC_CURRENT_EN               "E1 Stromstärke (mA)"
#define TMC_MODE_CONF_TITLE_EN          "Maschineneinstellungen>TMC Schrittmodus"
#define X_TMC_MODE_EN                   "X-Achse StealthChop Modus aktivieren?"
#define Y_TMC_MODE_EN                   "Y-Achse StealthChop Modus aktivieren?"
#define Z_TMC_MODE_EN                   "Z-Achse StealthChop Modus aktivieren?"
#define E0_TMC_MODE_EN                  "E0 StealthChop Modus aktivieren?"
#define E1_TMC_MODE_EN                  "E1 StealthChop Modus aktivieren?"
#define MOTORDIR_CONF_TITLE_EN          "Maschineneinstellungen>Motorrichtung"
#define X_MOTORDIR_EN                   "X-Achsen Motorrichtung invertieren"
#define Y_MOTORDIR_EN                   "Y-Achsen Motorrichtung invertieren"
#define Z_MOTORDIR_EN                   "Z-Achsen Motorrichtung invertieren"
#define E0_MOTORDIR_EN                  "E0 Motorrichtung invertieren"
#define E1_MOTORDIR_EN                  "E1 Motorrichtung invertieren"
#define INVERT_P_EN                     "JA"
#define INVERT_N_EN                     "NEIN"
#define HOMEFEEDRATE_CONF_TITLE_EN      "Maschineneinstellungen>Referenzfahrgeschwindigkeit"
#define X_HOMESPEED_EN                  "XY-Achsen Referenzfahrgeschwindigkeit"
#define Y_HOMESPEED_EN                  "Y-Achsen Referenzfahrgeschwindigkeit"
#define Z_HOMESPEED_EN                  "Z-Achsen Referenzfahrgeschwindigkeit"
#define ADVANCED_CONF_TITLE_EN          "Maschineneinstellungen>Erweitert"
#define PWROFF_DECTION_EN               "Stromausfallerkennungsmodul"
#define PWROFF_AFTER_PRINT_EN           "Automatisches Herunterfahren nach dem Druck"
#define HAVE_UPS_EN                     "Verfügtueber USV-Stromversorgung"
#define Z2_AND_Z2ENDSTOP_CONF_EN        "Z2 Einstellungen"
#define ENABLE_PINS_CONF_EN             "Enable-Pin Pegel-Einstellungen"
#define WIFI_SETTINGS_EN                "WLAN Parameter-Einstellungen"
#define HOMING_SENSITIVITY_CONF_EN      "Referenzfahr-Empfindlichkeitseinstellungen"
#define ENCODER_SETTINGS_EN             "Drehencoder-Einstellungen"
#define Z2_AND_Z2ENDSTOP_CONF_TITLE_EN  "Z2 Einstellungen"
#define Z2_ENABLE_EN                    "Z2 Aktivieren"
#define Z2_ENDSTOP_EN                   "Z2_EndStop Aktivieren"
#define Z2_PORT_EN                      "Z2 Stecker"
#define ENABLE_PINS_CONF_TITLE_EN       "ENABLE_PINS_LEVEL"
#define X_ENABLE_PINS_INVERT_EN         "X_ENABLE_PIN_INVERT"
#define Y_ENABLE_PINS_INVERT_EN         "Y_ENABLE_PIN_INVERT"
#define Z_ENABLE_PINS_INVERT_EN         "Z_ENABLE_PIN_INVERT"
#define E_ENABLE_PINS_INVERT_EN         "E_ENABLE_PIN_INVERT"
#define PAUSE_POSITION_EN    "Positionseinstellungen bei Druckpause"
#define PAUSE_POSITION_X_EN  "X-Achsen Position (Absolute Position,-1 ungültig)"
#define PAUSE_POSITION_Y_EN  "Y-Achsen Position (Absolute Position,-1 ungültig)"
#define PAUSE_POSITION_Z_EN  "Z-Achsen Position (Relative Position,-1 ungültig)"
#define WIFI_SETTINGS_TITLE_EN    "Maschineneinstellungen>WLAN Parameter"
#define WIFI_SETTINGS_MODE_EN     "WLAN Modus"
#define WIFI_SETTINGS_NAME_EN     "WLAN Name: "
#define WIFI_SETTINGS_PASSWORD_EN "WLAN Passwort: "
#define WIFI_SETTINGS_CLOUD_EN    "Möchten Sie Cloud-Dienste nutzen?"
#define WIFI_SETTINGS_CONFIG_EN   "Konfiguration"
#define WIFI_SETTINGS_EDIT_EN     "Bearbeiten"
#define WIFI_CONFIG_TIPS_EN       "WLAN konfigurieren?"
#define OFFSET_TITLE_EN  "Maschineneinstellungen>Offset"
#define OFFSET_X_EN      "X Offset"
#define OFFSET_Y_EN      "Y Offset"
#define OFFSET_Z_EN      "Z Offset"
#define HOMING_SENSITIVITY_CONF_TITLE_EN      "Maschineneinstellungen>Empfindlichkeit"
#define X_SENSITIVITY_EN                      "X-Achsen Empfindlichkeit"
#define Y_SENSITIVITY_EN                      "Y-Achsen Empfindlichkeit"
#define Z_SENSITIVITY_EN                      "Z-Achsen Empfindlichkeit"
#define Z2_SENSITIVITY_EN                     "Z2-Achsen Empfindlichkeit"
#define ENCODER_CONF_TITLE_EN                 "Maschineneinstellungen>Drehencoder Einstellungen"
#define ENCODER_CONF_TEXT_EN                  "Wird die Encoder-Funktion verwendet?"
#define TOOL_TEXT_EN            "Werkzeug"
#define PREHEAT_TEXT_EN         "Vorheizen"
#define MOVE_TEXT_EN            "Bewegen"
#define HOME_TEXT_EN            "Referenzfahrt"
#define PRINT_TEXT_EN           "Drucken"
#define EXTRUDE_TEXT_EN         "Extrudieren"
#define LEVELING_TEXT_EN        "Nivellieren"
#define AUTO_LEVELING_TEXT_EN   "AutoLevel"
#define SET_TEXT_EN             "Einstellungen"
#define MORE_TEXT_EN            "Mehr"
#define MORE_GCODE_EN           "G-Code"
#define MORE_ENTER_GCODE_EN     "G-Code eingeben"
#define ADD_TEXT_EN             "Hoeher"
#define DEC_TEXT_EN             "Niedriger"
#define EXTRUDER_1_TEXT_EN      "Extrusion1"
#define EXTRUDER_2_TEXT_EN      "Extrusion2"
#define HEATBED_TEXT_EN         "Heizbett"
#define TEXT_1C_EN              "1℃"
#define TEXT_5C_EN              "5℃"
#define TEXT_10C_EN             "10℃"
#define CLOSE_TEXT_EN           "Ausschalten"
#define BACK_TEXT_EN            "Zurück"
#define SAVE_TEXT_EN            "Speichern"
#define TOOL_PREHEAT_EN         "Vorheizen"
#define TOOL_EXTRUDE_EN         "Extrudieren"
#define TOOL_MOVE_EN            "Bewegen"
#define TOOL_HOME_EN            "Referenzfahrt"
#define TOOL_LEVELING_EN        "Nivellieren"
#define TOOL_AUTO_LEVELING_EN   "AutoLevel"
#define TOOL_FILAMENT_EN        "Filament"
#define TOOL_MORE_EN            "Mehr"
#define AXIS_X_ADD_TEXT_EN      "X+"
#define AXIS_X_DEC_TEXT_EN      "X-"
#define AXIS_Y_ADD_TEXT_EN      "Y+"
#define AXIS_Y_DEC_TEXT_EN      "Y-"
#define AXIS_Z_ADD_TEXT_EN      "Z+"
#define AXIS_Z_DEC_TEXT_EN      "Z-"
#define TEXT_01MM_EN            "0,1mm"
#define TEXT_1MM_EN             "1mm"
#define TEXT_10MM_EN            "10mm"
#define HOME_X_TEXT_EN          "X"
#define HOME_Y_TEXT_EN          "Y"
#define HOME_Z_TEXT_EN          "Z"
#define HOME_ALL_TEXT_EN        "Alle referenzieren"
#define HOME_STOPMOVE_EN        "Schnellstopp"
#define PAGE_UP_TEXT_EN         "Seite hoch"
#define PAGE_DOWN_TEXT_EN       "Seite runter"
#define EXTRUDER_IN_TEXT_EN           "Einlegen"
#define EXTRUDER_OUT_TEXT_EN          "Entnehmen"
#define EXTRUDE_1MM_TEXT_EN           "1mm"
#define EXTRUDE_5MM_TEXT_EN           "5mm"
#define EXTRUDE_10MM_TEXT_EN          "10mm"
#define EXTRUDE_LOW_SPEED_TEXT_EN     "Langsam"
#define EXTRUDE_MEDIUM_SPEED_TEXT_EN  "Normal"
#define EXTRUDE_HIGH_SPEED_TEXT_EN    "Schnell"
#define LEVELING_POINT1_TEXT_EN       "Punkt1"
#define LEVELING_POINT2_TEXT_EN       "Punkt2"
#define LEVELING_POINT3_TEXT_EN       "Punkt3"
#define LEVELING_POINT4_TEXT_EN       "Punkt4"
#define LEVELING_POINT5_TEXT_EN       "Punkt5"
#define FILESYS_TEXT_EN               "Dateisystem"
#define WIFI_TEXT_EN                  "WLAN"
#define FAN_TEXT_EN                   "Luefter"
#define ABOUT_TEXT_EN                 "Info"
#define BREAK_POINT_TEXT_EN           "Fortsetzen"
#define FILAMENT_TEXT_EN              "Filament"
#define LANGUAGE_TEXT_EN              "Sprache"
#define MOTOR_OFF_TEXT_EN             "Motoren aus"
#define MOTOR_OFF_XY_TEXT_EN          "Aus-XY"
#define SHUTDOWN_TEXT_EN              "Herunterfahren"
#define MACHINE_PARA_EN               "Konfiguration"
#define EEPROM_SETTINGS_EN            "EEPROM"
#define U_DISK_TEXT_EN                "USB"
#define SD_CARD_TEXT_EN               "SD"
#define WIFI_NAME_TEXT_EN             "WLAN: "
#define WIFI_KEY_TEXT_EN              "Schlüssel: "
#define WIFI_IP_TEXT_EN               "IP: "
#define WIFI_AP_TEXT_EN               "Status: AP"
#define WIFI_STA_TEXT_EN              "Status: STA"
#define WIFI_CONNECTED_TEXT_EN        "Verbunden"
#define WIFI_DISCONNECTED_TEXT_EN     "Nicht verbunden"
#define WIFI_EXCEPTION_TEXT_EN        "Ausnahme"
#define WIFI_RECONNECT_TEXT_EN        "Neuverbinden"
#define CLOUD_TEXT_EN                 "Cloud"
#define CLOUD_BIND_EN                 "Binden"
#define CLOUD_UNBIND_EN               "Lösen"
#define CLOUD_UNBINDING_EN            "Wird gelöst"
#define CLOUD_DISCONNECTED_EN         "Nicht verbunden"
#define CLOUD_UNBINDED_EN             "Gelöst"
#define CLOUD_BINDED_EN               "Gebunden"
#define CLOUD_DISABLE_EN              "Deaktivieren"
#define FAN_ADD_TEXT_EN               "Erhöhen"
#define FAN_DEC_TEXT_EN               "Verringern"
#define FAN_OPEN_TEXT_EN              "100%"
#define FAN_HALF_TEXT_EN              "50%"
#define FAN_CLOSE_TEXT_EN             "Aus"
#define FAN_TIPS1_TEXT_EN             "Luefter"
#define FAN_TIPS2_TEXT_EN             "Luefter AUS"
#define FILAMENT_IN_TEXT_EN           "Laden"
#define FILAMENT_OUT_TEXT_EN          "Entladen"
#define FILAMENT_EXT0_TEXT_EN         "Extrusion1"
#define FILAMENT_EXT1_TEXT_EN         "Extrusion2"
#define FILAMENT_HEAT_TEXT_EN         "Vorheizen"
#define FILAMENT_STOP_TEXT_EN         "Stoppen"
#define FILAMENT_TIPS2_TEXT_EN        "T:"
#define FILAMENT_TIPS3_TEXT_EN        "Laden..."
#define FILAMENT_TIPS4_TEXT_EN        "Entladen..."
#define FILAMENT_TIPS5_TEXT_EN        "Temperatur zu niedrig, bitte aufheizen"
#define FILAMENT_TIPS6_TEXT_EN        "Abgeschlossen"
#define FILAMENT_CHANGE_TEXT_EN                 "Bitte klicken Sie auf <Laden> \noder <Entladen>, nachdem \nder Drucker pausiert hat."
#define FILAMENT_DIALOG_LOAD_HEAT_TIPS_EN       "Düse wird aufgeheizt,\nbitte warten..."
#define FILAMENT_DIALOG_UNLOAD_HEAT_TIPS_EN     "Düse wird aufgeheizt,\nbitte warten..."
#define FILAMENT_DIALOG_LOAD_CONFIRM1_TIPS_EN   "Aufheizvorgang abgeschlossen, bitte Filament \nin den Extruder einlegen und <Bestätigen> drücken, \num mit dem Laden zu beginnen."
#define FILAMENT_DIALOG_LOAD_CONFIRM2_TIPS_EN   "Bitte legen Sie das Filament in den Extruder ein\nund drücken Sie <Bestätigen>, um mit dem Laden zu beginnen."
#define FILAMENT_DIALOG_UNLOAD_CONFIRM_TIPS_EN  "Aufheizvorgang abgeschlossen, bitte \ndrücken Sie <Bestätigen>, um mit dem Entladen zu beginnen!"
#define FILAMENT_DIALOG_LOADING_TIPS_EN         "Wird geladen, bitte warten!"
#define FILAMENT_DIALOG_UNLOADING_TIPS_EN       "Wird entladen, bitte warten!"
#define FILAMENT_DIALOG_LOAD_COMPLETE_TIPS_EN   "Filament laden abgeschlossen,\ndrücken Sie <Bestätigen>, um zurückzukehren!"
#define FILAMENT_DIALOG_UNLOAD_COMPLETE_TIPS_EN "Filament entladen abgeschlossen,\ndrücken Sie <Bestätigen>, um zurückzukehren!"
#define PRE_HEAT_EXT_TEXT_EN            "E"
#define PRE_HEAT_BED_TEXT_EN            "Bed"
#define FILE_LOADING_EN                 "Lade......"
#define NO_FILE_AND_CHECK_EN          "  Keine Dateien gefunden!\n           ueberprüfen Sie die Dateisystem-Konfiguration!"
#define NO_FILE_EN                          "Keine Dateien gefunden!"
#define EXTRUDER_TEMP_TEXT_EN               "Temperatur"
#define EXTRUDER_E_LENGTH1_TEXT_EN          "Extrusion1"
#define EXTRUDER_E_LENGTH2_TEXT_EN          "Extrusion2"
#define EXTRUDER_E_LENGTH3_TEXT_EN          "Extrusion3"
#define ABOUT_TYPE_TEXT_EN                  "Typ: "
#define ABOUT_VERSION_TEXT_EN               "Firmware: "
#define ABOUT_WIFI_TEXT_EN                  "WLAN: "
#define PRINTING_OPERATION_EN               "Option"
#define PRINTING_PAUSE_EN                   "Pause"
#define PRINTING_TEMP_EN                    "Temp."
#define PRINTING_CHANGESPEED_EN             "Geschwindigkeit"
#define PRINTING_RESUME_EN                  "Fortsetzen"
#define PRINTING_STOP_EN                    "Stoppen"
#define PRINTING_MORE_EN                    "Mehr"
#define PRINTING_EXTRUDER_EN                "Extrudieren"
#define PRINTING_MOVE_EN                    "Bewegen"
#define EXTRUDER_SPEED_EN                   "Extrusionsgeschwindigkeit"
#define MOVE_SPEED_EN                       "Bewegungsgeschwindigkeit"
#define EXTRUDER_SPEED_STATE_EN             "Extrusionsgeschwindigkeit"
#define MOVE_SPEED_STATE_EN                 "Bewegungsgeschwindigkeit"
#define STEP_1PERCENT_EN                    "1%"
#define STEP_5PERCENT_EN                    "5%"
#define STEP_10PERCENT_EN                   "10%"
#define TITLE_READYPRINT_EN                 "Bereit zum Drucken"
#define TITLE_PREHEAT_EN                    "Vorheizen"
#define TITLE_MOVE_EN                       "Bewegen"
#define TITLE_HOME_EN                       "Referenzfahrt"
#define TITLE_EXTRUDE_EN                    "Extrudieren"
#define TITLE_LEVELING_EN                   "Nivellieren"
#define TITLE_SET_EN                        "Einstellungen"
#define TITLE_MORE_EN                       "Mehr"
#define TITLE_CHOOSEFILE_EN                 "Datei auswählen"
#define TITLE_PRINTING_EN                   "Drucken"
#define TITLE_OPERATION_EN                  "Operation"
#define TITLE_ADJUST_EN                     "Justage"
#define TITLE_WIRELESS_EN                   "Drahtlos"
#define TITLE_FILAMENT_EN                   "Filament"
#define TITLE_ABOUT_EN                      "Über"
#define TITLE_FAN_EN                        "Luefter"
#define TITLE_LANGUAGE_EN                   "Sprache"
#define TITLE_PAUSE_EN                      "Pause"
#define TITLE_CHANGESPEED_EN                "Geschwindigkeit"
#define TITLE_CLOUD_TEXT_EN                 "Cloud"
#define TITLE_DIALOG_CONFIRM_EN             "Bestätigen"
#define TITLE_FILESYS_EN                    "Dateisystem"
#define AUTO_SHUTDOWN_EN                    "Auto"
#define MANUAL_SHUTDOWN_EN                  "Manuell"
#define DIALOG_CONFIRM_EN                   "Bestätigen"
#define DIALOG_CANCLE_EN                    "Abbrechen"
#define DIALOG_OK_EN                        "OK"
#define DIALOG_RESET_EN                     "Zurücksetzen"
#define DIALOG_RETRY_EN                     "Wiederholen"
#define DIALOG_DISABLE_EN                   "Deaktivieren"
#define DIALOG_PRINT_MODEL_EN               "Dieses Modell drucken?"
#define DIALOG_CANCEL_PRINT_EN              "Druck stoppen?"
#define DIALOG_RETRY_EN                     "Wiederholen"
#define DIALOG_STOP_EN                      "Stoppen"
#define DIALOG_REPRINT_FROM_BREAKPOINT_EN   "Vom letzten Punkt erneut drucken?"
#define DIALOG_ERROR_TIPS1_EN               "Fehler: keine Datei, bitte nochmals prüfen."
#define DIALOG_ERROR_TIPS2_EN               "Fehler:uebertragung fehlgeschlagen. Bitte prüfen Sie ob die Baudrate des Displays mit der Hauptplatineuebereinstimmt!"
#define DIALOG_ERROR_TIPS3_EN               "Fehler: Dateiname oder Pfad ist zu lang!"
#define DIALOG_CLOSE_MACHINE_EN             "Maschine wird heruntergefahren......"
#define DIALOG_UNBIND_PRINTER_EN            "Drucker lösen?"
#define DIALOG_FILAMENT_NO_PRESS_EN         "Filamentdetektorschalter nicht gedrückt"
#define DIALOG_PRINT_FINISH_EN              "Druck abgeschlossen!"
#define DIALOG_PRINT_TIME_EN                "Druckdauer: "
#define DIALOG_REPRINT_EN                   "Erneut drucken"
#define DIALOG_WIFI_ENABLE_TIPS_EN "Das WLAN-Modul wird konfiguriert\nbitte einen Moment warten....."
#define HOTBED_ENABLE_EN        "Heizbett aktivieren"
#define MOTOR_EN_HIGH_LEVEL_EN  "Hoch"
#define MOTOR_EN_LOW_LEVEL_EN   "Tief"
#define TEXT_WIFI_MENU_TITLE_EN "WLAN"
#define TEXT_WIFI_SAPCE_EN      "Leerzeichen"
#define TEXT_WIFI_LETTER_EN     "abc"
#define TEXT_WIFI_DIGITAL_EN    "123"
#define TEXT_WIFI_SYMBOL_EN     "#+="
#define TEXT_WIFI_PASSWORD_EN   "Passwort"
#define TEXT_WIFI_JOINING_EN  "Verbinde mit Netzwerk..."
#define TEXT_WIFI_FAILED_JOIN_EN  "Verbindung mit WLAN fehlgeschlagen"
#define TEXT_WIFI_WIFI_CONECTED_EN "WLAN Verbunden"
#define TEXT_BUTTON_DISCONECTED_EN  "Trennen"
#define TEXT_WIFI_FORGET_EN         "Netzwerk vergessen"
#define TEXT_DISCONECTED_EN         "WLAN Verbunden"
// wifi-list
#define MAIN_BUILT_EN       "Bauen"
#define MAIN_FILAMENT_EN    "Filament"
#define MAIN_SETUP_EN       "Setup"
#define MAIN_ABOUT_EN       "Über"
#define MAIN_MENU_EN        "Menü"
#define FILE_MENU_BUILD_EN  "Bauen"
#define FILE_MENU_MENU_EN   " < Menü"
// about
#define ABOUT_TITLE_EN                    "Über"
#define ABOUT_BUILT_MACHINES_EN           "Gebaute Maschinen"
#define ABOUT_SPARK_EN                    "Spark"
#define ABOUT_VERSION_EN                  "Version 1.1.0"
#define ABOUT_SERIAL_NUMBER_EN            "Seriennummer:"
#define ABOUT_S_NUMBER_EN                 "DCPLX02KFC6P"
// set
#define SETUP_TITLE_EN                    "Setup"
#define SETUP_WIFI_EN                     "WLAN"
#define SETUP_MANUAL_IP_EN                "Manuelle IP"
#define SETUP_WIFI_NOT_CONNECTED_EN       "Nicht verbunden"
#define SETUP_WIFI_NETWORK_EN             "WLAN_Netzwerk"
// build
#define BUILD_TITLE_EN                    "Bauen"
#define BUILD_SD_CARD_EN                  "SD Karte"
#define BUILD_USB_DRIVE_EN                "USB Speicher"
// SD card
#define SD_CARD_TITLE_EN                  "SD Karte"
#define SD_CARD_BACK_EN                   "< Zurück"
// USB Drive
#define USB_DRIVE_TITLE_EN                "USB Speicher"
#define USB_DRIVE_BACK_EN                 "< Zurück"
#define FILE_PAGES_EN                     "%d/%d"
#define FILE_NEXT_PAGE_EN                 "Nächste Seite"
#define MEDIA_SELECT_TITLE_EN             "Medium auswählen"
// BUILD PLATE
#define PLATE_TITLE_EN                    "Bauraumplatte"
#define PLATE_BACK_EN                     "< Zurück"
#define PLATE_CONFIRM_EN                  "Bestätigen >"
#define PLATE_TIPS_EN                     "Bestätigen Sie, dass eine leere \nBauraumplatte in der \nMaschine installiert ist."
// build model
#define MODEL_TITLE_EN                    "Modelldruck"
#define MODEL_START_BUILD_EN              "Druck starten"
#define MODEL_BACK_EN                     "< Zurück"
// building
#define BUILDING_TITLE_EN                 "Wird gebaut"
#define BUILDING_MENU_EN                  "Druckmenü"
#define BUILDING_COMPLETED                "Druck \nabgeschlossen"
// building menu
#define BUILDING_MENU_TITLE_EN            "Druckmenü"
#define BUILDING_MENU_SETTINGS_EN         "Druckeinstellungen"
#define BUILDING_MENU_PAUSE_EN            "Druck pausieren"
#define BUILDING_MENU_CANCEL_EN           "Druck abbrechen"
#define BUILDING_MENU_BACK_EN             "< Zurück"
// build settings
#define SETTINGS_TITLE_EN                 "Druckeinstellungen"
#define SETTINGS_NOZZLE_TEMPER_EN         "Düsentemperatur:"
#define SETTINGS_NOZZLE_VALUE_EN          "%d"
#define SETTINGS_BED_TEMPER_EN            "Betttemperatur:"
#define SETTINGS_BED_VALUE_EN             "%d"
#define SETTINGS_BUILD_SPEED_EN           "Druckgeschwindigkeit:"
#define SETTINGS_SPEED_VALUE_EN           "Standard"
#define SETTINGS_BACK_EN                  "< Zurück"
// build paused
#define PAUSED_TITLE_EN                   "Druck pausiert"
#define PAUSED_RESUME_EN                  "Druck fortsetzen"
#define PAUSED_CANCEL_EN                  "Druck abbrechen"
#define PAUSED_BACK_EN                    "< Zurück"
// build cancel
#define CANCEL_TITLE_EN                   "Druck abbrechen"
#define CANCEL_BUILD_EN                   "Druck abbrechen"
#define CANCEL_TIPS_EN                    "Sind Sie sicher, dass Sie \ndiesen Druck abbrechen möchten? Das Modell \nwird von dieser \nMaschine gelöscht. Es muss \nvon Ihrem Computer neu \ngesendet werden, bevor es \nerneut gedruckt werden kann."
#define CANCEL_BACK_EN                    "< Zurück"
#define CANCEL_BUILD_DISPLAY_EN           "Druck \nabgebrochen"
#define CANCEL_OVER_PLATE_TIPS_EN         "Bestätigen Sie, dass die Bauraumplatte \naus der \nMaschine entfernt wurde."
// filament model enter
#define FILAMENT_MODEL_ENTER_TITLE_EN     "Modell-PLA"
#define FILAMENT_MODEL_ENTER_BACK_EN      "< Zurück"
#define FILAMENT_MODEL_ENTER_BEGIN_EN     "Beginnen >"
#define FILAMENT_MODEL_ENTER_TIPS_EN      "Das Modellfilament-Spulenfach \nbefindet sich auf \nder rechten Seite der Maschine."
// filament model PLA
#define FILAMENT_MODEL_PLA_TITLE_EN       "Modell-PLA"
#define FILAMENT_PLA_LOAD_TITLE_EN        "Filament laden"
#define FILAMENT_PLA_UNLOAD_TITLE_EN      "Filament entladen"
#define FILAMENT_MODEL_PLA_LOAD_EN        "Filament laden"
#define FILAMENT_MODEL_PLA_UNLOAD_EN      "Filament entladen"
// filament support enter
#define FILAMENT_SUPPORT_ENTER_TITLE_EN   "Support-PVA"
#define FILAMENT_SUPPORT_ENTER_BACK_EN    "< Zurück"
#define FILAMENT_SUPPORT_ENTER_BEGIN_EN   "Beginnen >"
#define FILAMENT_SUPPORT_ENTER_TIPS_EN    "Das Supportfilament-Spulenfach \nbefindet sich auf \nder linken Seite der Maschine."
// filament heating
#define FILAMENT_HEATING_LOAD_TITLE_EN    "Filament laden"
#define FILAMENT_HEATING_UNLOAD_TITLE_EN  "Filament entladen"
#define FILAMENT_HEATING_CANCEL_EN        "< Abbrechen"
#define FILAMENT_HEATING_MATERIAL_EN      "Material:"
#define FILAMENT_HEATING_PLA_EN           "Modell-PLA"
#define FILAMENT_HEATING_TIPS_EN          "Druckkopf wird aufgeheizt..."
// rotate left
#define ROTATE_LEFT_LOAD_TITLE_EN         "Filament laden"
#define ROTATE_LEFT_UNLOAD_TITLE_EN       "Filament entladen"
#define ROTATE_LEFT_CANCEL_EN             "< Abbrechen"
#define ROTATE_LEFT_MATERIAL_EN           "Material:"
#define ROTATE_LEFT_PLA_EN                "Modell-PLA"
#define ROTATE_LEFT_NEXT_EN               "Weiter >"
#define ROTATE_LEFT_TIPS_EN               "Drehen Sie das Extruder-Auswahlsymbol \nlinks herum."
// hang spool
#define HANG_SPOOL_TITLE_EN         "Filament laden"
#define HANG_SPOOL_PREVIOUS_EN      "< Zurück"
#define HANG_SPOOL_MATERIAL_EN      "Material:"
#define HANG_SPOOL_PLA_EN           "Modell-PLA"
#define HANG_SPOOL_NEXT_EN          "Weiter >"
#define HANG_SPOOL_TIPS_EN          "Hängen Sie die Spule in das Spulenfach \nwie dargestellt."
// feed filament
#define FEED_FILAMENT_TITLE_EN      "Filament laden"
#define FEED_FILAMENT_PREVIOUS_EN   "< Zurück"
#define FEED_FILAMENT_MATERIAL_EN   "Material:"
#define FEED_FILAMENT_PLA_EN        "Modell-PLA"
#define FEED_FILAMENT_NEXT_EN       "Weiter >"
#define FEED_FILAMENT_TIPS_EN       "Führen Sie das Filament in den Extruder \nüber die Zahnräder hinaus."
// feed filament
#define ROTATE_UP_TITLE_EN          "Filament laden"
#define ROTATE_UP_PREVIOUS_EN        "< Zurück"
#define ROTATE_UP_MATERIAL_EN       "Material:"
#define ROTATE_UP_PLA_EN            "Modell-PLA"
#define ROTATE_UP_NEXT_EN           "Weiter >"
#define ROTATE_UP_TIPS_EN           "Drehen Sie das Extruder-Auswahlsymbol \nnach oben."
// filament begin
#define FEED_BEGIN_TITLE_EN         "Filament laden"
#define FEED_BEGIN_MATERIAL_EN      "Material:"
#define FEED_BEGIN_PLA_EN           "Modell-PLA"
#define FEED_BEGIN_NEXT_EN          "Weiter >"
#define FEED_BEGIN_TIPS_EN          "Drücken Sie Weiter, wenn das Filament \nanfängt extrudiert zu werden."
// filament finish
#define FEED_FINISH_TITLE_EN        "Filament laden"
#define FEED_FINISH_MATERIAL_EN     "Material:"
#define FEED_FINISH_PLA_EN          "Modell-PLA"
#define FEED_FINISH_NEXT_EN         "Fertig >"
#define FEED_FINISH_TIPS_EN         "Entfernen Sie das Filament von der \nDüse und entsorgen Sie es."
// fiament remove
#define REMOVE_SPOOL_TITLE_EN       "Filament entladen"
#define REMOVE_SPOOL_PREVIOUS_EN     "< Zurück"
#define REMOVE_SPOOL_FINISH_EN      "Fertig >"
#define REMOVE_SPOOL_MATERIAL_EN    "Material:"
#define REMOVE_SPOOL_PLA_EN         "Modell-PLA"
#define REMOVE_SPOOL_TIPS_EN        "Entfernen Sie die Spule und ziehen Sie \ndas Filament aus der Maschine."
#define FILAMENT_SUPPORT_PVA_EN     "Support-PVA"
#define LOAD_FINISH_EN              "Filament \nladen \nabgeschlossen"
#define UNLOAD_FINISH_EN            "Filament \nentladen \nabgeschlossen"
// manual ip
#define MANUAL_IP_TITLE_EN          "Manuelle IP"
#define MANUAL_IP_CANCEL_EN         "< Abbrechen"
#define MANUAL_IP_APPLY_EN          "Verbinden >"
#define MANUAL_IP_ADDRESS_EN        "IP Adresse"
#define MANUAL_IP_MASK_EN           "Subnetzmaske"
#define MANUAL_IP_GATEWAY_EN        "Standardgateway"
#define MANUAL_IP_SERVER_EN         "Nameserver"
#define MANUAL_IP_INIT_DATA_EN      "0.0.0.0"
#define MANUAL_TEXT_POINT_EN        "."
#define MANUAL_TEXT_ENTER_EN        "Eingabe"
#define TEXT_FORGET_TIPS_TITLE_EN "Netzwerk vergessen"
#define TEXT_FORGET_NETWORK_TIPS1_EN "Sind Sie sicher, dass Sie dieses \nNetzwerk vergessen möchten?"
#define TEXT_FORGET_NETWORK_TIPS2_EN "Diese Maschine wird sich nicht mehr \nmit diesem WLAN-Netzwerk verbinden."
#define TEXT_IPADDRESS_EN "IP Adresse: "
#define TEXT_BUILD_FROM_CURA_CANCEL_TIPS1_EN "Sind Sie sicher, dass Sie diesen \nDruck abbrechen möchten?"
#define TEXT_BUILD_FROM_CURA_CANCEL_TIPS2_EN "Das Modell wird von dieser \nMaschine gelöscht. Es muss \nvon Ihrem Computer neu \ngesendet werden, bevor es \nerneut gedruckt werden kann."
#define DIALOG_CONFIRM_EN2              "Bestätigen"
#define HEATING_TITLE_EN  "Aufheizen"
#define LEVELING_TITLE_EN  "Nivellieren"
#define ABOUT_SPARK_ADD_EN "Spark+"
#define TEXT_RECEIVING_DATA_EN "Daten werden empfangen"
#define TEXT_BABY_STEP_EN "Feinjustage"
#define PRINTING_OTHER_LANGUGE              "Drucken"
#define PRINTING_OPERATION_OTHER_LANGUGE    "Option"
#define PRINTING_PAUSE_OTHER_LANGUGE        "Pause"
#define MESSAGE_PAUSING_EN        "Parkposition anfahren..."
#define MESSAGE_CHANGING_EN       "Warten auf Filamentwechsel"
#define MESSAGE_UNLOAD_EN         "Warten auf Filamententnahme"
#define MESSAGE_WAITING_EN        "Drücken Sie die Taste, um fortzufahren"
#define MESSAGE_INSERT_EN         "Legen Sie Filament ein und drücken Sie die Taste, um fortzufahren"
#define MESSAGE_LOAD_EN           "Warten auf Filamentladen"
#define MESSAGE_PURGE_EN          "Warten auf Filamentreinigung"
#define MESSAGE_RESUME_EN         "Warten auf Druckfortsetzung..."
#define MESSAGE_HEAT_EN           "Drücken Sie die Taste, um die Düse aufzuheizen"
#define MESSAGE_HEATING_EN        "Düse heizt vor - bitte warten..."
#define MESSAGE_OPTION_EN         "Reinigen oder Druck fortsetzen?"
#define MESSAGE_PURGE_MORE_EN     "Reinigen"
#define MESSAGE_CONTINUE_PRINT_EN "Drucken"
#define EEPROM_SETTINGS_TITLE_EN  "EEPROM Einstellungen"
#define EEPROM_SETTINGS_STORE_EN  "Einstellungen im EEPROM speichern"
#define EEPROM_SETTINGS_READ_EN   "Einstellungen vom EEPROM lesen"
#define EEPROM_SETTINGS_REVERT_EN "Einstellungen auf Werkseinstellungen zurücksetzen"
#define EEPROM_STORE_TIPS_EN  "Einstellungen im EEPROM speichern?"
#define EEPROM_READ_TIPS_EN   "Einstellungen vom EEPROM lesen?"
#define EEPROM_REVERT_TIPS_EN "Einstellungen auf Werkseinstellungen zurücksetzen?"
#define MORE_CUSTOM1_TEXT_EN  MAIN_MENU_ITEM_1_DESC
#define MORE_CUSTOM2_TEXT_EN  MAIN_MENU_ITEM_2_DESC
#define MORE_CUSTOM3_TEXT_EN  MAIN_MENU_ITEM_3_DESC
#define MORE_CUSTOM4_TEXT_EN  MAIN_MENU_ITEM_4_DESC
#define MORE_CUSTOM5_TEXT_EN  MAIN_MENU_ITEM_5_DESC
#define MORE_CUSTOM6_TEXT_EN  MAIN_MENU_ITEM_6_DESC
